import { dehydrate, HydrationBoundary } from "@tanstack/react-query";
import type { Metadata } from "next";
import { Geist_Mono, Stack_Sans_Notch } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Toaster } from "sonner";
import "./globals.css";
import { getQueryClient } from "./lib/query/get-query-client";
import { regionQueries } from "./modules/region/queries";
import { storeQueries } from "./modules/store/queries";
import { QueryProvider } from "./providers/query-provider";

const stackSans = Stack_Sans_Notch({
  variable: "--font-stack-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = getQueryClient();

  // Fetch store config (also populates cache for client)
  const storeConfig = await queryClient.fetchQuery(
    storeQueries.getStoreConfig.queryOptions(),
  );

  // Prefetch default region using the store's default_region_id
  if (storeConfig.default_region_id) {
    queryClient.prefetchQuery(
      regionQueries.getRegion.queryOptions(storeConfig.default_region_id),
    );
  }

  return (
    <html lang="en">
      <body
        className={`${stackSans.variable} ${geistMono.variable} font-sans antialiased`}
      >
        <QueryProvider>
          <HydrationBoundary state={dehydrate(queryClient)}>
            <NuqsAdapter>
              {children}
              <Toaster />
            </NuqsAdapter>
          </HydrationBoundary>
        </QueryProvider>
      </body>
    </html>
  );
}
